#!/bin/sh
set -euo pipefail

system_type=$(uname -s)

if [ "$system_type" = "Darwin" ]; then

  # install homebrew if it's missing
  if ! command -v brew >/dev/null 2>&1; then
    echo "Installing homebrew"
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  fi

  if [ -f "$HOME/.Brewfile" ]; then
    echo "Updating homebrew bundle"
    # create local Brewfile if it doesn't already exist
    touch ~/.Brewfile.local
    brew bundle --global
  fi

  # set up mac defaults, must log out/log in to take effect
  echo "Configuring Mac settings"
  defaults write -g InitialKeyRepeat -int 10 # normal minimum is 15 (225 ms)
  defaults write -g KeyRepeat -int 2 # normal minimum is 2 (30 ms)
  defaults write -g AppleInterfaceStyle -string Dark

fi

if [ ! -d "$HOME/.tmux/plugins/tpm" ]; then
  git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
  ~/.tmux/plugins/tpm/scripts/install_plugins.sh
fi

if [ ! -d "$HOME/.oh-my-zsh" ]; then
  echo "Installing Oh-My-Zsh"
  sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
fi

if [ ! -d "$HOME/.oh-my-zsh/custom/themes/powerlevel10k" ]; then
  echo "Installing Powerlevel10k"
  git clone --depth=1 https://github.com/romkatv/powerlevel10k.git $HOME/.oh-my-zsh/custom/themes/powerlevel10k
fi

if [ ! -d "$HOME/.oh-my-zsh/custom/plugins/zsh-autosuggestions" ]; then
  echo "Installing ZSH Autosuggestions"
	git clone https://github.com/zsh-users/zsh-autosuggestions $HOME/.oh-my-zsh/custom/plugins/zsh-autosuggestions
fi

if [ ! -d "$HOME/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting" ]; then
  echo "Installing ZSH Syntax Highlighting"
	git clone https://github.com/zsh-users/zsh-syntax-highlighting.git $HOME/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting
fi

if [ ! -d "$HOME/.ddev/themes" ]; then
  echo "Generating themes"
  mkdir /tmp/base16-shell
  git clone https://github.com/chriskempson/base16-shell.git /tmp/base16-shell
  cp -r /tmp/base16-shell/scripts $HOME/.ddev/themes
  rm -rf /tmp/base16-shell
  source $HOME/.ddev/source/_ddev_convert_theme_file
  for theme in $HOME/.ddev/themes/*; do _ddev_convert_theme_file $theme; done
  rm $HOME/.ddev/themes/base16-*
fi

if [ ! -f "$HOME/.ddev/source/z.sh" ]; then
  echo "Installing Z"
  curl --output $HOME/.ddev/source/z.sh https://raw.githubusercontent.com/rupa/z/master/z.sh
fi

if command -v nvim >/dev/null 2>&1; then
  echo "Bootstraping nvim"
  nvim '+PlugUpdate' '+PlugClean!' '+PlugUpdate' '+qall'
fi

if [ -z "$(pyenv versions --bare)" ]; then
  echo "Installing global Python version"
  pyenv install "$(pyenv latest --known 3)"
fi

if [ "$(pyenv global)" = "system" ]; then
  echo "Setting global python version to $(pyenv versions --bare | tail -1)"
  pyenv global "$(pyenv versions --bare | tail -1)"
fi

echo "Installing global Python requirements"
PYTHON="$(PYENV_VERSION=$(pyenv global) pyenv which python)"
"${PYTHON}" -m pip install --upgrade pip
"${PYTHON}" -m pip install --upgrade --requirement ~/requirements.txt
